name: demo 
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Step 1
      run: |
        echo "Step 1 executed"
    
    - name: Step 2
      run: |
        echo "Step 2 executed"
    
    - name: Step 3
      run: |
        echo "Step 3 executed"

    - name: Step 4
      run: |
        echo "Step 4 executed"

    - name: Step 5
      run: |
        echo "Step 5 executed"
    
    - name: Final Step
      run: |
        echo "Final Step executed"

    - name: Adding markdown
      run: |
         echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY  
         ID=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
         echo "$ID" >> $GITHUB_STEP_SUMMARY
         echo "Job status: ${{ job.status }} ">> $GITHUB_STEP_SUMMARY
    - name: demo_test
      run: |
          {
            echo "### :rocket: Workflow inputs"
            echo "| Arg                 | Value |"
            echo "| ------------------- | ----- |"
            echo "| Print inputs        | ${{ inputs.print-inputs }} |"
            echo "| Environment         | ${{ inputs.environment }} |"
            echo "| Cluster             | ${{ inputs.cluster }} |"
          } >> $GITHUB_STEP_SUMMARY     
#  summary: |
#     Steps:
#     - Step 1: ${{ job.steps.step1.outcome }}
#     - Step 2: ${{ job.steps.step2.outcome }}
#     - Step 3: ${{ job.steps.step3.outcome }}       
  
  # summary: |
  #   Steps:
  #   - Step 1
  #   - Step 2
  #   - Step 3
  #   - Step 4
  #   - Step 5
  #   - Final Step
