name: red
on: push
jobs:
   first-job:
      runs-on: ubuntu-latest
      steps:
         - name: step 1
           run: echo "Hello world"

         - name: step 2
           run: |
              curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/jobs/${{ github.job }}  

         - name: print url
           run: |
              echo "Print url: https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/jobs/${{ github.job }}" >> $GITHUB_STEP_SUMMARY