name: test workflow
on: push
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
        - name: run echo command
          run: echo "Hello World"
        - name: print gihub workflow id
          run: echo "Your workflow id is ${{ github.run_id }}"