name: test workflow
on: push
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
        - name: run echo command
          run: echo "Hello World"
        - name: print gihub workflow id
          run: |
              echo "Your workflow id is ${{ github.run_id }}" >> $GITHUB_STEP_SUMMARY 
              echo "Home: ${HOME}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_ACTOR: ${GITHUB_ACTOR}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_SHA: ${GITHUB_SHA}" >> $GITHUB_STEP_SUMMARY 
              echo "GITHUB_REF: ${GITHUB_REF}" >> $GITHUB_STEP_SUMMARY 
        - name: show github env
          run: |
              echo "Path to workflow ${GITHUB_WORKFLOW_REF}" >> $GITHUB_STEP_SUMMARY 
              echo "Name of workflow ${GITHUB_WORKFLOW}" >> $GITHUB_STEP_SUMMARY 
              echo "${{ github.job}}" >> $GITHUB_STEP_SUMMARY 
              echo "${{ github.run_id}}" >> $GITHUB_STEP_SUMMARY 
              echo "${GITHUB_RUN_NUMBER}" >> $GITHUB_STEP_SUMMARY 
              echo "${RUN_ID}" >> $GITHUB_STEP_SUMMARY 
              echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${{github.run_id}}/${{ github.job }}" >> $GITHUB_STEP_SUMMARY 
              echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" >> $GITHUB_STEP_SUMMARY 


        # - name: demo
        #   run: |
        #       ID=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
        #       echo "$ID"     
        #       headers='Content-Type: application/json'
        #       abc=$(curl --location -w "%http_code" --request GET "$ID" --header "$headers")
        #       # echo "$abc"
                 
        #       responseCode=$(tail -n1 <<< "$abc")
        #       echo $responseCode  
        #       if [[ "$responseCode" == "200" ]]; then
        #           echo "Code ran successfull"
        #       fi    

        # - name: Make HTTP Request
        #   id: http_request
        #   run: |
        #     ID=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
        #     status_code=$(curl --write-out "%{http_code}" --silent --output /dev/null "$ID")
        #     echo "::set-output name=status_code::$status_code"
        #     echo $responseCode  
        #     if [[ "$status_code" == "200" ]]; then
        #         echo "Code ran successfull"
        #     fi  

        # - name: Check Status Code
        #   run: |
        #     echo "The HTTP status code is: ${{ steps.http_request.outputs.status_code }}"
        - name: Adding markdown
          run: |
            echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY  
            ID=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
            echo "$ID" >> $GITHUB_STEP_SUMMARY
            echo "Job status: ${{ job.status }} ">> $GITHUB_STEP_SUMMARY

        - name: demo_test
          run: |
              {
                echo "### :rocket: Workflow inputs"
                echo "| Arg                 | Value |"
                echo "| ------------------- | ----- |"
                echo "| Print inputs        | ${{ inputs.print-inputs }} |"
                echo "| Environment         | ${{ inputs.environment }} |"
                echo "| Cluster             | ${{ inputs.cluster }} |"
              } >> $GITHUB_STEP_SUMMARY     
