name: test workflow
on: push
jobs:
   job1:
      runs-on: ubuntu-latest
      steps:
        - name: run echo command
          run: echo "Hello World"
        - name: print gihub workflow id
          run: |
              echo "Your workflow id is ${{ github.run_id }}"
              echo "Home: ${HOME}"
              echo "GITHUB_WORKFLOW: ${GITHUB_WORKFLOW}"
              echo "GITHUB_ACTIONS: ${GITHUB_ACTIONS}"
              echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
              echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
              echo "GITHUB_EVENT_NAME: ${GITHUB_EVENT_NAME}"
              echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
              echo "GITHUB_SHA: ${GITHUB_SHA}"
              echo "GITHUB_REF: ${GITHUB_REF}"
        - name: show github env
          run: |
              echo "Path to workflow ${GITHUB_WORKFLOW_REF}"
              echo "Name of workflow ${GITHUB_WORKFLOW}"
              echo "${{ github.job}}"
              echo "${{ github.run_id}}"
              echo "${GITHUB_RUN_NUMBER}"
              echo "${RUN_ID}"
              echo "https://github.com/${GITHUB_REPOSITORY}/actions/runs/${{github.run_id}}/${{ github.job }}"
              echo "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"


        - name: demo
          run: |
              ID=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID 
              echo "$ID"     
              headers='Content-Type: application/json'
              abc=$(curl --location -w "%http_code" --request GET "$ID" --header "$headers")
              echo "$abc"
                 